name: Package Build

on: [push, pull_request]

jobs:
  packaging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout github repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tool
        run: pip install build

      - name: Build wheel and sdist
        run: python -m build

      - name: Test install from wheel
        run: |
          pip install dist/*.whl
          python -c "import rate_runner; print('Import succeeded')"

